# Spring Boot application configuration
spring:
  # General application settings
  application:
    name: NeloRestaurant

  # Data source configuration for Oracle database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: your-username
    password: password
    driver-class-name: org.postgresql.Driver

  # JDBC settings
  jdbc:
  # Optionally configure connection pool settings
  # For example:
  # initialize:
  #   mode: always

  # Server settings
  server:
    port: 8080  # Port on which the application runs

  # Logging settings
  logging:
    level:
      root: INFO  # Log level for root logger
      com.example: DEBUG  # Log level for specific package

# Custom application properties (if needed)
custom:
  property1: value1
  property2: value2
